# Generated by Django 3.2.3 on 2021-06-04 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_city',
            new_name='city',
        ),
    ]
