# Generated by Django 3.2.3 on 2021-05-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('job_type', models.CharField(choices=[('1', 'Full Time'), ('2', 'Part Time')], default='1', max_length=20)),
                ('description', models.TextField()),
                ('published_at', models.TimeField()),
                ('Vacancy', models.FloatField()),
                ('salary', models.FloatField()),
                ('category', models.FloatField()),
                ('experience', models.CharField(max_length=120)),
            ],
        ),
    ]
