# Generated by Django 3.2.3 on 2021-05-31 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_job_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aplly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=100)),
                ('website', models.URLField()),
                ('upload_cv', models.FileField(upload_to='apply/')),
                ('cover_leter', models.TextField(max_length=500)),
            ],
        ),
    ]
