# Generated by Django 3.2.3 on 2021-05-31 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_aplly'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aplly',
            new_name='Apply',
        ),
    ]
